-- NutriVane schema (idempotent). Dijalankan otomatis oleh backend saat startup,
-- dan bisa juga dijalankan manual di Supabase Dashboard -> SQL Editor.
-- Catatan: pisahkan setiap statement dengan ';' (backend mengeksekusi file ini apa adanya).

create table if not exists public.categories (
  key text primary key,
  label text not null,
  sort_order int not null default 0
);

create table if not exists public.recipes (
  slug text primary key,
  name text not null,
  category text not null references public.categories(key),
  category_label text not null,
  porsi int not null default 1,
  image text not null default '',
  tagline text not null default '',
  flavor_note text not null default '',
  spices jsonb not null default '[]'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.moods (
  key text primary key,
  label text not null,
  emoji text not null default '',
  subtitle text not null default '',
  question text not null default '',
  helper text not null default '',
  recipe_slugs jsonb not null default '[]'::jsonb,
  sort_order int not null default 0
);

create table if not exists public.insights (
  slug text primary key references public.recipes(slug) on delete cascade,
  text text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key,
  email text,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  user_id uuid,
  benchmark_slug text not null references public.recipes(slug),
  measure boolean not null default false,
  had_image boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists scans_user_created_idx on public.scans(user_id, created_at desc);

create table if not exists public.favorites (
  user_id uuid not null,
  slug text not null references public.recipes(slug) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, slug)
);
